# Tarea M31-AD – Jorge Ruiz

## Manipulación y análisis de datos FIFA con Pandas

En este notebook se utilizará Pandas para realizar análisis estadístico,
agrupaciones, incorporación de nuevos registros y creación de nuevas
variables mediante funciones lambda.

In [1]:
import pandas as pd

ruta = r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\fifa_eda.csv"

df_fifa = pd.read_csv(ruta)

In [2]:
df_fifa.sample(20)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
965,230463,Simão Acunha,30,Brazil,77,77,Atlético Mineiro,8500.0,35.0,Right,1.0,4.0,CAM,2018,2021-01-01,5.833333,157.0,16200.000000
11119,232733,A. Fukuta,26,Japan,64,65,Sagan Tosu,525.0,1.0,Right,1.0,3.0,RAM,2014,2021-01-01,5.583333,143.0,696.000000
9501,156321,A. Akinfenwa,36,England,66,66,Wycombe Wanderers,230.0,2.0,Right,1.0,2.0,LS,2016,2019-01-01,5.833333,243.0,403.000000
14976,215425,F. Sachpekidis,20,Sweden,60,72,Kalmar FF,375.0,1.0,Right,1.0,3.0,LM,2013,2020-01-01,5.916667,168.0,544.000000
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.000000
10392,222836,R. Ledson,20,England,65,77,Preston North End,950.0,3.0,Right,1.0,3.0,CM,2018,2021-01-01,5.916667,152.0,2000.000000
14893,231262,Leja,23,Spain,60,69,Granada CF,240.0,1.0,Right,1.0,1.0,GK,2017,2019-01-01,6.000000,170.0,432.000000
11716,209071,Y. Hamza,27,Saudi Arabia,64,64,Al Fateh,375.0,6.0,Right,1.0,2.0,CB,2018,2019-01-01,6.000000,168.0,619.000000
4721,176630,Marco Rocha,31,Portugal,71,71,Santa Clara,1400.0,3.0,Right,1.0,1.0,GK,2017,2019-01-01,6.000000,183.0,3000.000000
16551,245173,O. Mireles,19,Mexico,57,70,Club León,170.0,2.0,Right,1.0,2.0,CB,2018,2021-01-01,5.833333,150.0,395.000000
13090,242183,D. Otto,19,Germany,62,81,TSG 1899 Hoffenheim,650.0,3.0,Right,1.0,3.0,ST,2018,2021-01-01,6.083333,181.0,1500.000000
8771,204033,N. Devlin,24,Scotland,66,68,Walsall,650.0,2.0,Right,1.0,2.0,RB,2017,2019-01-01,6.000000,161.0,1200.000000
5365,188336,A. Tuia,28,Italy,70,72,Benevento,1700.0,3.0,Right,1.0,2.0,CB,2018,2021-01-01,6.000000,163.0,2800.000000
17283,244225,A. Groundstroem,18,Sweden,54,64,IF Brommapojkarna,90.0,1.0,Right,1.0,2.0,CB,2018,2018-01-01,6.083333,165.0,131.000000
3302,186651,G. Vural,30,Turkey,72,72,Akhisar Belediyespor,2900.0,13.0,Left,1.0,3.0,LB,2018,2021-01-01,5.833333,143.0,5900.000000
7952,237383,A. Bastoni,19,Italy,67,87,Parma,1500.0,7.0,Left,1.0,2.0,CB,2016,2019-06-30,6.250000,165.0,4585.060806
15487,229718,W. Patching,19,England,59,73,Notts County,325.0,1.0,Right,1.0,2.0,CM,2018,2020-01-01,6.083333,154.0,772.000000
10294,240729,L. Rajot,20,France,65,75,Clermont Foot 63,775.0,1.0,Right,1.0,3.0,CDM,2017,2020-01-01,5.833333,150.0,1500.000000
15499,224602,Zhang Wei,25,China PR,59,63,Shanghai SIPG FC,170.0,2.0,Left,1.0,2.0,LB,2014,2020-01-01,5.750000,161.0,387.000000
11091,223767,O. Özdemir,23,Turkey,64,70,1. FC Kaiserslautern,525.0,1.0,Right,1.0,2.0,CB,2018,2021-01-01,6.166667,185.0,866.000000

In [3]:
df_fifa.sample(20)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
13880,237550,H. Ndam,19,Cameroon,62,72,New York Red Bulls,425.0,1.0,Right,1.0,2.0,CB,2017,2019-01-01,6.333333,209.0,723.000000
7657,238594,A. Dej,26,Poland,67,70,SSV Jahn Regensburg,925.0,4.0,Right,1.0,2.0,CM,2018,2020-01-01,5.750000,163.0,1500.000000
5647,208898,D. Łukasik,27,Poland,69,69,Lechia Gdańsk,875.0,4.0,Right,1.0,2.0,CDM,2014,2021-01-01,5.833333,161.0,1200.000000
8044,211288,L. Domínguez,28,Chile,67,68,CD Everton de Viña del Mar,700.0,2.0,Left,1.0,2.0,CB,2018,2019-01-01,6.166667,170.0,998.000000
761,223874,V. Rongier,23,France,78,83,FC Nantes,14000.0,25.0,Right,2.0,3.0,RCM,2014,2022-01-01,5.666667,154.0,27700.000000
15108,244921,Sergio Moreno,19,Spain,60,73,Rayo Vallecano,400.0,2.0,Right,1.0,2.0,ST,2018,2019-01-01,5.916667,165.0,1100.000000
7577,173040,A. Bonnet,31,France,68,68,Le Havre AC,775.0,4.0,Left,1.0,3.0,LM,2009,2019-01-01,5.666667,143.0,1400.000000
16765,191559,S. Kawamata,28,Japan,56,56,Kashima Antlers,60.0,1.0,Right,1.0,1.0,GK,2014,2021-01-01,6.166667,190.0,78.000000
9740,224217,R. van der Meer,23,Netherlands,66,70,Excelsior,700.0,2.0,Left,1.0,2.0,LB,2018,2021-01-01,6.416667,190.0,1100.000000
9089,209223,A. Al Faraj,29,Saudi Arabia,66,66,Al Nassr,500.0,10.0,Right,1.0,3.0,LB,2012,2020-01-01,5.666667,150.0,850.000000
15510,239201,A. Ceylan,20,Germany,59,70,SC Fortuna Köln,270.0,1.0,Right,1.0,3.0,LM,2017,2019-01-01,5.583333,143.0,446.000000
13763,233934,A. Ramsdale,20,England,62,76,Bournemouth,550.0,4.0,Right,1.0,1.0,GK,2017,2021-01-01,6.166667,170.0,1400.000000
568,229909,A. Lunev,26,Russia,79,81,NaN,NaN,0.0,Right,1.0,1.0,GK,2016,NaN,6.166667,176.0,4585.060806
1019,154472,Jorge Molina,36,Spain,77,77,Getafe CF,3200.0,20.0,Right,1.0,3.0,RS,2016,2019-01-01,6.166667,159.0,6700.000000
2617,204549,D. Roef,24,Belgium,73,77,Waasland-Beveren,3700.0,10.0,Right,1.0,1.0,GK,2016,2019-06-30,6.166667,190.0,4585.060806
2138,172835,M. Andreolli,32,Italy,74,74,Cagliari,3200.0,25.0,Right,2.0,2.0,CB,2017,2019-01-01,6.166667,176.0,5500.000000
16270,231935,R. Kim,21,Russia,58,68,Pohang Steelers,160.0,1.0,Right,1.0,1.0,GK,2015,2020-01-01,6.250000,181.0,232.000000
9988,244238,J. Bijol,19,Slovenia,65,78,PFC CSKA Moscow,900.0,1.0,Right,1.0,2.0,CDM,2018,2023-01-01,6.250000,187.0,2500.000000
17494,242910,Liu Boyang,21,China PR,54,61,Beijing Renhe FC,80.0,1.0,Right,1.0,2.0,RB,2018,2020-01-01,5.750000,150.0,188.000000
7915,244287,M. Vrushaj,19,Albania,67,80,Olympiacos CFP,1400.0,1.0,Right,1.0,3.0,LM,2016,2019-01-01,5.833333,168.0,4000.000000

In [4]:
estadisticas_generales = df_fifa[
    ["Age", "Overall", "Potential"]
].agg(["mean", "min", "max"])

estadisticas_generales

            Age    Overall  Potential
mean  25.122206  66.238699  71.307299
min   16.000000  46.000000  48.000000
max   45.000000  94.000000  95.000000

In [5]:
estadisticas_pais = (
    df_fifa
    .groupby("Nationality")[["Age", "Overall", "Potential"]]
    .agg(["mean", "min", "max"])
)

estadisticas_pais

                   Age            Overall          Potential
                  mean min max       mean min max       mean min max
Nationality
Afghanistan  22.500000  20  26  61.000000  59  63  67.750000  64  71
Albania      24.025000  18  34  65.925000  52  81  71.700000  62  86
Algeria      27.050000  19  35  70.633333  58  85  72.983333  62  85
Andorra      28.000000  28  28  62.000000  62  62  64.000000  64  64
Angola       25.866667  19  34  67.600000  60  78  71.533333  64  82
...                ...  ..  ..        ...  ..  ..        ...  ..  ..
Uzbekistan   29.500000  29  30  67.500000  60  75  67.500000  60  75
Venezuela    24.313433  18  34  67.268657  53  81  73.149254  55  84
Wales        24.736434  17  37  64.139535  47  88  69.968992  56  88
Zambia       22.222222  18  29  65.222222  56  73  73.777778  66  83
Zimbabwe     26.846154  22  34  69.769231  64  78  72.461538  66  83

[164 rows x 9 columns]

In [6]:
estadisticas_pais.loc["Mexico"]

Age        mean    24.319672
           min     17.000000
           max     45.000000
Overall    mean    65.418033
           min     50.000000
           max     82.000000
Potential  mean    71.508197
           min     57.000000
           max     86.000000
Name: Mexico, dtype: float64

In [7]:
print("Número de columnas:", len(df_fifa.columns))
print(df_fifa.columns.tolist())

Número de columnas: 18
['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value', 'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight', 'Release Clause']

In [8]:
jugador1 = df_fifa.iloc[0].copy()
jugador2 = df_fifa.iloc[1].copy()

In [9]:
jugador1["ID"] = 999001
jugador1["Name"] = "Jorge Ruiz"
jugador1["Age"] = 25
jugador1["Nationality"] = "Mexico"
jugador1["Overall"] = 88
jugador1["Potential"] = 90
jugador1["Club"] = "FC Data Analytics"

jugador2["ID"] = 999002
jugador2["Name"] = "Alex Torres"
jugador2["Age"] = 22
jugador2["Nationality"] = "Mexico"
jugador2["Overall"] = 82
jugador2["Potential"] = 84
jugador2["Club"] = "Python United"

In [10]:
nuevos_jugadores = pd.DataFrame([jugador1, jugador2])

df_fifa = pd.concat(
    [df_fifa, nuevos_jugadores],
    ignore_index=True
)

In [11]:
df_fifa.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18207,999001,Jorge Ruiz,25,Mexico,88,90,FC Data Analytics,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
18208,999002,Alex Torres,22,Mexico,82,84,Python United,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [12]:
estadisticas_nuevas = df_fifa[
    ["Age", "Overall", "Potential"]
].agg(["mean", "min", "max"])

estadisticas_nuevas

            Age   Overall  Potential
mean  25.122028  66.24076  71.309023
min   16.000000  46.00000  48.000000
max   45.000000  94.00000  95.000000

In [13]:
estadisticas_antes = estadisticas_generales.copy()

In [14]:
estadisticas_despues = df_fifa[
    ["Age", "Overall", "Potential"]
].agg(["mean", "min", "max"])

In [15]:
print("ESTADÍSTICAS ANTES:")
display(estadisticas_antes)

print("ESTADÍSTICAS DESPUÉS:")
display(estadisticas_despues)

ESTADÍSTICAS ANTES:

            Age    Overall  Potential
mean  25.122206  66.238699  71.307299
min   16.000000  46.000000  48.000000
max   45.000000  94.000000  95.000000

ESTADÍSTICAS DESPUÉS:

            Age   Overall  Potential
mean  25.122028  66.24076  71.309023
min   16.000000  46.00000  48.000000
max   45.000000  94.00000  95.000000

### Comparación

Después de añadir los dos jugadores ficticios, se calcularon nuevamente
la media, el mínimo y el máximo de las variables Age, Overall y Potential.

La media puede presentar pequeñas variaciones debido a la incorporación
de los nuevos registros, mientras que los valores mínimos y máximos
solamente cambiarán si alguno de los nuevos jugadores supera los límites
existentes en el dataset original.

In [16]:
info_paises = {
    "Mexico": ("Mexico City", "UTC-6"),
    "Argentina": ("Buenos Aires", "UTC-3"),
    "Brazil": ("Brasilia", "UTC-3"),
    "Spain": ("Madrid", "UTC+1"),
    "France": ("Paris", "UTC+1"),
    "Germany": ("Berlin", "UTC+1"),
    "England": ("London", "UTC+0"),
    "Portugal": ("Lisbon", "UTC+0"),
    "Italy": ("Rome", "UTC+1"),
    "Belgium": ("Brussels", "UTC+1")
}

In [17]:
df_fifa["Capital"] = df_fifa["Nationality"].apply(
    lambda pais: info_paises.get(pais, ("No disponible", "No disponible"))[0]
)

df_fifa["Zona_Horaria"] = df_fifa["Nationality"].apply(
    lambda pais: info_paises.get(pais, ("No disponible", "No disponible"))[1]
)

In [18]:
df_fifa[
    ["Name", "Nationality", "Capital", "Zona_Horaria"]
].head(20)

                 Name Nationality        Capital   Zona_Horaria
0            L. Messi   Argentina   Buenos Aires          UTC-3
1   Cristiano Ronaldo    Portugal         Lisbon          UTC+0
2           Neymar Jr      Brazil       Brasilia          UTC-3
3              De Gea       Spain         Madrid          UTC+1
4        K. De Bruyne     Belgium       Brussels          UTC+1
5           E. Hazard     Belgium       Brussels          UTC+1
6           L. Modrić     Croatia  No disponible  No disponible
7           L. Suárez     Uruguay  No disponible  No disponible
8        Sergio Ramos       Spain         Madrid          UTC+1
9            J. Oblak    Slovenia  No disponible  No disponible
10     R. Lewandowski      Poland  No disponible  No disponible
11           T. Kroos     Germany         Berlin          UTC+1
12           D. Godín     Uruguay  No disponible  No disponible
13        David Silva       Spain         Madrid          UTC+1
14           N. Kanté      France          Paris          UTC+1
15          P. Dybala   Argentina   Buenos Aires          UTC-3
16            H. Kane     England         London          UTC+0
17       A. Griezmann      France          Paris          UTC+1
18      M. ter Stegen     Germany         Berlin          UTC+1
19        T. Courtois     Belgium       Brussels          UTC+1

In [19]:
df_fifa["Candidato"] = df_fifa["Potential"].apply(
    lambda potencial: "Candidato" if potencial > 85 else "Next Year"
)

In [20]:
df_fifa[
    ["Name", "Overall", "Potential", "Candidato"]
].head(20)

                 Name  Overall  Potential  Candidato
0            L. Messi       94         94  Candidato
1   Cristiano Ronaldo       94         94  Candidato
2           Neymar Jr       92         93  Candidato
3              De Gea       91         93  Candidato
4        K. De Bruyne       91         92  Candidato
5           E. Hazard       91         91  Candidato
6           L. Modrić       91         91  Candidato
7           L. Suárez       91         91  Candidato
8        Sergio Ramos       91         91  Candidato
9            J. Oblak       90         93  Candidato
10     R. Lewandowski       90         90  Candidato
11           T. Kroos       90         90  Candidato
12           D. Godín       90         90  Candidato
13        David Silva       90         90  Candidato
14           N. Kanté       89         90  Candidato
15          P. Dybala       89         94  Candidato
16            H. Kane       89         91  Candidato
17       A. Griezmann       89         90  Candidato
18      M. ter Stegen       89         92  Candidato
19        T. Courtois       89         90  Candidato

In [21]:
candidatos = df_fifa[
    df_fifa["Candidato"] == "Candidato"
]

candidatos[
    ["Name", "Nationality", "Overall", "Potential", "Candidato"]
]

                    Name Nationality  Overall  Potential  Candidato
0               L. Messi   Argentina       94         94  Candidato
1      Cristiano Ronaldo    Portugal       94         94  Candidato
2              Neymar Jr      Brazil       92         93  Candidato
3                 De Gea       Spain       91         93  Candidato
4           K. De Bruyne     Belgium       91         92  Candidato
...                  ...         ...      ...        ...        ...
9935          C. Früchtl     Germany       65         86  Candidato
10801          E. Ampadu       Wales       65         86  Candidato
11457        W. Geubbels      France       64         86  Candidato
13927            A. Dabo      France       62         86  Candidato
18207         Jorge Ruiz      Mexico       88         90  Candidato

[275 rows x 5 columns]

In [22]:
print("Número de candidatos:", len(candidatos))

Número de candidatos: 275

In [23]:
df_fifa.tail(2)[
    ["Name", "Nationality", "Overall", "Potential",
     "Capital", "Zona_Horaria", "Candidato"]
]

,Name,Nationality,Overall,Potential,Capital,Zona_Horaria,Candidato
18207,Jorge Ruiz,Mexico,88,90,Mexico City,UTC-6,Candidato
18208,Alex Torres,Mexico,82,84,Mexico City,UTC-6,Next Year