# Tarea M28 – Jorge Ruiz

## Manejo de archivos con Python y Pandas

En este notebook se realizará la lectura y manipulación de tres fuentes
de datos diferentes: CSV, Excel y JSON.

Para cada archivo se realizarán las siguientes operaciones:

- Lectura del archivo.
- Conversión de los datos a una lista.
- Obtención de las primeras 10 filas.
- Obtención de las últimas 10 filas.
- Selección de columnas.
- Generación de un nuevo archivo con las columnas seleccionadas.

In [1]:
import pandas as pd

## Ejercicio 1: Archivo CSV - FIFA

Se realizará la lectura y manipulación del archivo `fifa_eda.csv`
utilizando la biblioteca Pandas.

In [3]:
import pandas as pd

In [5]:
import os

print(os.getcwd())

C:\Users\jorge

In [6]:
print(os.listdir())

['.anaconda', '.conda', '.continuum', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.templateengine', '.viminfo', '04_dashboard_dataset.ipynb', 'anaconda3', 'anaconda_projects', 'AnalisisDelictivo', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TM.blf', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TM.blf.cnpf', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{1a93417b-ac17-11f1-9bfb-7c5079a8c329}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Tarea M27-AD – JORGE EDUARDO RUIZ GAYTAN.ipynb', 'Tarea M28 – JORGE EDUARDO RUIZ GAYTAN.ipynb', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Videos']

In [9]:
df_fifa = pd.read_csv(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\fifa_eda.csv"
)

df_fifa.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

In [10]:
lista_fifa = df_fifa.values.tolist()

print(lista_fifa[:5])

[[158023, 'L. Messi', 31, 'Argentina', 94, 94, 'FC Barcelona', 110500.0, 565.0, 'Left', 5.0, 4.0, 'RF', 2004, '2021-01-01', 5.583333333333333, 159.0, 226500.0], [20801, 'Cristiano Ronaldo', 33, 'Portugal', 94, 94, 'Juventus', 77000.0, 405.0, 'Right', 5.0, 5.0, 'ST', 2018, '2022-01-01', 6.166666666666667, 183.0, 127100.0], [190871, 'Neymar Jr', 26, 'Brazil', 92, 93, 'Paris Saint-Germain', 118500.0, 290.0, 'Right', 5.0, 5.0, 'LW', 2017, '2022-01-01', 5.75, 150.0, 228100.0], [193080, 'De Gea', 27, 'Spain', 91, 93, 'Manchester United', 72000.0, 260.0, 'Right', 4.0, 1.0, 'GK', 2011, '2020-01-01', 6.333333333333333, 168.0, 138600.0], [192985, 'K. De Bruyne', 27, 'Belgium', 91, 92, 'Manchester City', 102000.0, 355.0, 'Right', 4.0, 4.0, 'RCM', 2015, '2023-01-01', 5.916666666666667, 154.0, 196400.0]]

In [11]:
df_fifa.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
9,200389,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.0

In [12]:
df_fifa.tail(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18197,246167,D. Holland,18,Republic of Ireland,47,61,Cork City,60.0,1.0,Right,1.0,2.0,CM,2018,2018-01-01,5.833333,141.0,88.0
18198,242844,J. Livesey,18,England,47,70,Burton Albion,60.0,1.0,Right,1.0,1.0,GK,2018,2021-01-01,5.916667,154.0,165.0
18199,244677,M. Baldisimo,18,Canada,47,69,Vancouver Whitecaps FC,70.0,1.0,Right,1.0,2.0,CM,2018,2021-01-01,5.500000,150.0,175.0
18200,231381,J. Young,18,Scotland,47,62,Swindon Town,60.0,1.0,Left,1.0,2.0,ST,2015,2019-01-01,5.750000,157.0,143.0
18201,243413,D. Walsh,18,Republic of Ireland,47,68,Waterford FC,60.0,1.0,Left,1.0,2.0,RB,2018,2018-01-01,6.083333,168.0,153.0
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [13]:
print(df_fifa.columns.tolist())

['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value', 'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight', 'Release Clause']

In [14]:
fifa_seleccion = df_fifa[["Name", "Age", "Overall", "Club"]]

fifa_seleccion.head(10)

                Name  Age  Overall                 Club
0           L. Messi   31       94         FC Barcelona
1  Cristiano Ronaldo   33       94             Juventus
2          Neymar Jr   26       92  Paris Saint-Germain
3             De Gea   27       91    Manchester United
4       K. De Bruyne   27       91      Manchester City
5          E. Hazard   27       91              Chelsea
6          L. Modrić   32       91          Real Madrid
7          L. Suárez   31       91         FC Barcelona
8       Sergio Ramos   32       91          Real Madrid
9           J. Oblak   25       90      Atlético Madrid

In [15]:
fifa_seleccion.to_csv(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\fifa_seleccion.csv",
    index=False
)

print("Archivo fifa_seleccion.csv creado correctamente.")

Archivo fifa_seleccion.csv creado correctamente.

## Ejercicio 2: Archivo Excel - Best Selling Novels

En este ejercicio se realizará la lectura y manipulación de un archivo
Excel utilizando Pandas.

In [20]:
df_novels = pd.read_excel(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\Amazon_top100_bestselling_books_2009to2021.xlsx"
)

df_novels.head()

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
0,0,12.49,1.0,The Lost Symbol,16118.0,4.4,Dan Brown,Hardcover,2009,Fiction
1,1,13.40,2.0,The Shack: Where Tragedy Confronts Eternity,23392.0,4.7,William P. Young,Paperback,2009,Fiction
2,2,9.93,3.0,Liberty and Tyranny: A Conservative Manifesto,5036.0,4.8,Mark R. Levin,Hardcover,2009,Non Fiction
3,3,14.30,4.0,"Breaking Dawn (The Twilight Saga, Book 4)",16912.0,4.7,Stephenie Meyer,Hardcover,2009,Fiction
4,4,9.99,5.0,Going Rogue: An American Life,1572.0,4.6,Sarah Palin,Hardcover,2009,Non Fiction

In [21]:
lista_novels = df_novels.values.tolist()

print(lista_novels[:5])

[[0, 12.49, 1.0, 'The Lost Symbol', 16118.0, 4.4, 'Dan Brown', 'Hardcover', 2009, 'Fiction'], [1, 13.4, 2.0, 'The Shack: Where Tragedy Confronts Eternity', 23392.0, 4.7, 'William P. Young', 'Paperback', 2009, 'Fiction'], [2, 9.93, 3.0, 'Liberty and Tyranny: A Conservative Manifesto', 5036.0, 4.8, 'Mark R. Levin', 'Hardcover', 2009, 'Non Fiction'], [3, 14.3, 4.0, 'Breaking Dawn (The Twilight Saga, Book 4)', 16912.0, 4.7, 'Stephenie Meyer', 'Hardcover', 2009, 'Fiction'], [4, 9.99, 5.0, 'Going Rogue: An American Life', 1572.0, 4.6, 'Sarah Palin', 'Hardcover', 2009, 'Non Fiction']]

In [22]:
df_novels.head(10)

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
0,0,12.49,1.0,The Lost Symbol,16118.0,4.4,Dan Brown,Hardcover,2009,Fiction
1,1,13.40,2.0,The Shack: Where Tragedy Confronts Eternity,23392.0,4.7,William P. Young,Paperback,2009,Fiction
2,2,9.93,3.0,Liberty and Tyranny: A Conservative Manifesto,5036.0,4.8,Mark R. Levin,Hardcover,2009,Non Fiction
3,3,14.30,4.0,"Breaking Dawn (The Twilight Saga, Book 4)",16912.0,4.7,Stephenie Meyer,Hardcover,2009,Fiction
4,4,9.99,5.0,Going Rogue: An American Life,1572.0,4.6,Sarah Palin,Hardcover,2009,Non Fiction
5,5,18.29,6.0,StrengthsFinder 2.0,7082.0,4.1,Gallup,Hardcover,2009,Non Fiction
6,6,12.66,7.0,The Help,18068.0,4.8,Kathryn Stockett,Hardcover,2009,Fiction
7,7,17.56,8.0,New Moon (The Twilight Saga),12329.0,4.7,Stephenie Meyer,Paperback,2009,Fiction
8,8,58.90,9.0,The Twilight Saga Collection,6100.0,4.7,Stephenie Meyer,Hardcover,2009,Fiction
9,9,16.04,10.0,Outliers: The Story of Success,22209.0,4.7,Malcolm Gladwell,Hardcover,2009,Non Fiction

In [23]:
df_novels.tail(10)

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
1281,1281,11.94,91.0,The Step-by-Step Instant Pot Cookbook: 100 Sim...,30581.0,4.7,Jeffrey Eisner,Paperback,2021,Non Fiction
1282,1282,12.32,92.0,The Vanishing Half: A Novel,96412.0,4.4,Brit Bennett,Hardcover,2021,Fiction
1283,1283,16.53,93.0,A Promised Land,125017.0,4.9,Barack Obama,Hardcover,2021,Non Fiction
1284,1284,11.89,94.0,What Should Danny Do? (The Power to Choose Ser...,22169.0,4.8,Adir Levy,Hardcover,2021,Fiction
1285,1285,13.40,95.0,The Wish,35292.0,4.7,Nicholas Sparks,Hardcover,2021,Fiction
1286,1286,16.69,96.0,Will,21401.0,4.8,Will Smith,Hardcover,2021,Non Fiction
1287,1287,7.49,97.0,Think and Grow Rich: The Landmark Bestseller N...,79872.0,4.7,Napoleon Hill,Paperback,2021,Non Fiction
1288,1288,8.95,98.0,Dragons Love Tacos,15753.0,4.8,Adam Rubin,Hardcover,2021,Fiction
1289,1289,7.59,99.0,The Truth About COVID-19: Exposing The Great R...,7246.0,4.8,Doctor Joseph Mercola,Hardcover,2021,Non Fiction
1290,1290,13.29,100.0,First Little Readers Parent Pack: Guided Readi...,27332.0,4.7,Deborah Schecter,Paperback,2021,Non Fiction

In [24]:
print(df_novels.columns.tolist())

['Unnamed: 0', 'price', 'ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year', 'genre']

In [25]:
print(df_novels.columns.tolist())

['Unnamed: 0', 'price', 'ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year', 'genre']

In [26]:
novels_seleccion = df_novels[["title", "author", "ratings", "year"]]

novels_seleccion.head(10)

,title,author,ratings,year
0,The Lost Symbol,Dan Brown,4.4,2009
1,The Shack: Where Tragedy Confronts Eternity,William P. Young,4.7,2009
2,Liberty and Tyranny: A Conservative Manifesto,Mark R. Levin,4.8,2009
3,"Breaking Dawn (The Twilight Saga, Book 4)",Stephenie Meyer,4.7,2009
4,Going Rogue: An American Life,Sarah Palin,4.6,2009
5,StrengthsFinder 2.0,Gallup,4.1,2009
6,The Help,Kathryn Stockett,4.8,2009
7,New Moon (The Twilight Saga),Stephenie Meyer,4.7,2009
8,The Twilight Saga Collection,Stephenie Meyer,4.7,2009
9,Outliers: The Story of Success,Malcolm Gladwell,4.7,2009

In [27]:
novels_seleccion.to_excel(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\novels_seleccion.xlsx",
    index=False
)

print("Archivo novels_seleccion.xlsx creado correctamente.")

Archivo novels_seleccion.xlsx creado correctamente.

## Ejercicio 3: Archivo JSON - Game of Thrones Subtitles

En este ejercicio se realizará la lectura y manipulación de un archivo
JSON correspondiente a la primera temporada de Game of Thrones.

In [28]:
df_got = pd.read_json(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\GOT Subtitles\season1.json"
)

df_got.head()

,Game Of Thrones S01E01 Winter Is Coming.srt,Game Of Thrones S01E02 The Kingsroad.srt,Game Of Thrones S01E03 Lord Snow.srt,"Game Of Thrones S01E04 Cripples, Bastards, And Broken Things.srt",Game Of Thrones S01E05 The Wolf And The Lion.srt,Game Of Thrones S01E06 A Golden Crown.srt,Game Of Thrones S01E07 You Win Or You Die.srt,Game Of Thrones S01E08 The Pointy End.srt,Game Of Thrones S01E09 Baelor.srt,Game Of Thrones S01E10 Fire And Blood.srt
1,"Easy, boy.","You need to drink, child.","Welcome, Lord Stark.",The little lord's been dreaming again.,Does Ser Hugh have any family in the capital?,"Your pardon, Your Grace.","""Summoned to court to answer for the crimes","Yah! Left high, left low.","You've seen better days, my lord.",Look at me. Look at me!
10,Our orders were to track the wildlings.,The Dothraki believe that one day,Sturdy old thing.,- Hodor? - Help Bran down the hall.,But who holds the straws?,He butchered my men.,"Go on, say something clever.",Go back to your room.,I've given up trying to guess.,"It told me to come with him, so I did."
100,- Right. Give it here. - No!,Such a little thing.,That's not true. You killed the beast.,We're done for today. Go clean the armoury.,# In garb of red and gold #,Drop the blade!,Your sister was a corpse and I was a living girl,"- We should burn them. - Snow's not wrong, my ...",- Oh! - You too.,This one here.
101,Put away your blade.,A bird without feathers.,You only spared the girl because of the love y...,That's all you're good for.,This isn't the Kingsroad.,"- No, don't. - Do it.",and he loved her more than me.,Fire will do for them. The wildling way.,You see that?,Look at it and see what happens to traitors.
102,"- I take orders from your father, not you. - P...",They came to take his body away,"I didn't, I...",- Well fought! - Piss off.,- You said we were riding for Winterfell. - I ...,Are you all right?,"When the king returns from his hunt, I'll tell...",I want Maester Aemon to examine them first.,"Fifteen, she is.",- You promised to be merciful. - I was.

In [29]:
lista_got = df_got.values.tolist()

print(lista_got[:5])

[['Easy, boy.', 'You need to drink, child.', 'Welcome, Lord Stark.', "The little lord's been dreaming again.", 'Does Ser Hugh have any family in the capital?', 'Your pardon, Your Grace.', '"Summoned to court to answer for the crimes', 'Yah! Left high, left low.', "You've seen better days, my lord.", 'Look at me. Look at me!'], ['Our orders were to track the wildlings.', 'The Dothraki believe that one day', 'Sturdy old thing.', '- Hodor? - Help Bran down the hall.', 'But who holds the straws?', 'He butchered my men.', 'Go on, say something clever.', 'Go back to your room.', "I've given up trying to guess.", 'It told me to come with him, so I did.'], ['- Right. Give it here. - No!', 'Such a little thing.', "That's not true. You killed the beast.", "We're done for today. Go clean the armoury.", '# In garb of red and gold #', 'Drop the blade!', 'Your sister was a corpse and I was a living girl', "- We should burn them. - Snow's not wrong, my lord.", '- Oh! - You too.', 'This one here.'], ['Put away your blade.', 'A bird without feathers.', 'You only spared the girl because of the love your father bears her father.', "That's all you're good for.", "This isn't the Kingsroad.", "- No, don't. - Do it.", 'and he loved her more than me.', 'Fire will do for them. The wildling way.', 'You see that?', 'Look at it and see what happens to traitors.'], ['- I take orders from your father, not you. - Please, Father!', 'They came to take his body away', "I didn't, I...", '- Well fought! - Piss off.', '- You said we were riding for Winterfell. - I did... Often and loudly.', 'Are you all right?', "When the king returns from his hunt, I'll tell him the truth.", 'I want Maester Aemon to examine them first.', 'Fifteen, she is.', '- You promised to be merciful. - I was.']]

In [30]:
df_got.head(10)

,Game Of Thrones S01E01 Winter Is Coming.srt,Game Of Thrones S01E02 The Kingsroad.srt,Game Of Thrones S01E03 Lord Snow.srt,"Game Of Thrones S01E04 Cripples, Bastards, And Broken Things.srt",Game Of Thrones S01E05 The Wolf And The Lion.srt,Game Of Thrones S01E06 A Golden Crown.srt,Game Of Thrones S01E07 You Win Or You Die.srt,Game Of Thrones S01E08 The Pointy End.srt,Game Of Thrones S01E09 Baelor.srt,Game Of Thrones S01E10 Fire And Blood.srt
1,"Easy, boy.","You need to drink, child.","Welcome, Lord Stark.",The little lord's been dreaming again.,Does Ser Hugh have any family in the capital?,"Your pardon, Your Grace.","""Summoned to court to answer for the crimes","Yah! Left high, left low.","You've seen better days, my lord.",Look at me. Look at me!
10,Our orders were to track the wildlings.,The Dothraki believe that one day,Sturdy old thing.,- Hodor? - Help Bran down the hall.,But who holds the straws?,He butchered my men.,"Go on, say something clever.",Go back to your room.,I've given up trying to guess.,"It told me to come with him, so I did."
100,- Right. Give it here. - No!,Such a little thing.,That's not true. You killed the beast.,We're done for today. Go clean the armoury.,# In garb of red and gold #,Drop the blade!,Your sister was a corpse and I was a living girl,"- We should burn them. - Snow's not wrong, my ...",- Oh! - You too.,This one here.
101,Put away your blade.,A bird without feathers.,You only spared the girl because of the love y...,That's all you're good for.,This isn't the Kingsroad.,"- No, don't. - Do it.",and he loved her more than me.,Fire will do for them. The wildling way.,You see that?,Look at it and see what happens to traitors.
102,"- I take orders from your father, not you. - P...",They came to take his body away,"I didn't, I...",- Well fought! - Piss off.,- You said we were riding for Winterfell. - I ...,Are you all right?,"When the king returns from his hunt, I'll tell...",I want Maester Aemon to examine them first.,"Fifteen, she is.",- You promised to be merciful. - I was.
103,"I'm sorry, Bran.","and Robert held me. I screamed and I battled, ...","When Aerys Targaryen sat on the iron throne, y...",- Did he hurt you? - I've had worse.,"Very wise. They'll be out in droves,",Yes. It doesn't hurt.,You must be gone by then - you and your children.,"You may be a coward, Tarly, but you're not stu...",A little flower.,I gave him a clean death.
104,Lord Stark?,That little bundle.,Someday you'll sit on the throne and the truth...,You can call me Sam... if you want.,looking for me in the wrong place.,Tough little lad.,I will not have their blood on my hands.,- Get them inside. - You heard him.,And her honey's all mine.,Look at him.
105,There are five pups.,They took him away and I never saw him again.,Do I have to marry her?,- My mother calls me Sam. - It's not going to ...,Word's probably gotten to my father by now.,"In the Iron Islands, you're not a man until yo...","Go as far away as you can,","Lord Commander,",I'm sure she will give you many sons.,"Please let me go home. I won't do any treason,..."
106,One for each of the Stark children.,"Never have visited the crypt, never.",Yes.,- You're going to have to defend yourself. - W...,He'll be offering a handsome reward.,Well done.,with as many men as you can.,Maester Aemon awaits you in his chambers...,Huh. Your father didn't come to the wedding.,Mother says I'm still to marry you. So you'll ...
107,The direwolf is the sigil of your house.,I pray to the Mother every morning and night,She's very beautiful and young.,I wanted to.,Everyone knows a Lannister always pays his debts.,Have you lost your mind?,"Because wherever you go,",A raven from King's Landing.,"He is quite ill, my lord.",Look at him!

In [31]:
df_got.tail(10)

,Game Of Thrones S01E01 Winter Is Coming.srt,Game Of Thrones S01E02 The Kingsroad.srt,Game Of Thrones S01E03 Lord Snow.srt,"Game Of Thrones S01E04 Cripples, Bastards, And Broken Things.srt",Game Of Thrones S01E05 The Wolf And The Lion.srt,Game Of Thrones S01E06 A Golden Crown.srt,Game Of Thrones S01E07 You Win Or You Die.srt,Game Of Thrones S01E08 The Pointy End.srt,Game Of Thrones S01E09 Baelor.srt,Game Of Thrones S01E10 Fire And Blood.srt
766,NaN,NaN,NaN,NaN,NaN,NaN,You think he stands alone?,NaN,NaN,NaN
767,NaN,NaN,NaN,NaN,NaN,NaN,Kill him! Kill all of them! I command it!,NaN,NaN,NaN
768,NaN,NaN,NaN,NaN,NaN,NaN,Commander! Take the queen and her children int...,NaN,NaN,NaN
769,NaN,NaN,NaN,NaN,NaN,NaN,Escort them back to the royal apartments and k...,NaN,NaN,NaN
770,NaN,NaN,NaN,NaN,NaN,NaN,Men of the Watch!,NaN,NaN,NaN
771,NaN,NaN,NaN,NaN,NaN,NaN,I want no bloodshed.,NaN,NaN,NaN
772,NaN,NaN,NaN,NaN,NaN,NaN,Tell your men to lay down their swords.,NaN,NaN,NaN
773,NaN,NaN,NaN,NaN,NaN,NaN,No one needs to die.,NaN,NaN,NaN
774,NaN,NaN,NaN,NaN,NaN,NaN,Now!,NaN,NaN,NaN
775,NaN,NaN,NaN,NaN,NaN,NaN,I did warn you not to trust me.,NaN,NaN,NaN

In [32]:
print(df_got.columns.tolist())

['Game Of Thrones S01E01 Winter Is Coming.srt', 'Game Of Thrones S01E02 The Kingsroad.srt', 'Game Of Thrones S01E03 Lord Snow.srt', 'Game Of Thrones S01E04 Cripples, Bastards, And Broken Things.srt', 'Game Of Thrones S01E05 The Wolf And The Lion.srt', 'Game Of Thrones S01E06 A Golden Crown.srt', 'Game Of Thrones S01E07 You Win Or You Die.srt', 'Game Of Thrones S01E08 The Pointy End.srt', 'Game Of Thrones S01E09 Baelor.srt', 'Game Of Thrones S01E10 Fire And Blood.srt']

In [33]:
got_seleccion = df_got.iloc[:, 0:4]

got_seleccion.head(10)

,Game Of Thrones S01E01 Winter Is Coming.srt,Game Of Thrones S01E02 The Kingsroad.srt,Game Of Thrones S01E03 Lord Snow.srt,"Game Of Thrones S01E04 Cripples, Bastards, And Broken Things.srt"
1,"Easy, boy.","You need to drink, child.","Welcome, Lord Stark.",The little lord's been dreaming again.
10,Our orders were to track the wildlings.,The Dothraki believe that one day,Sturdy old thing.,- Hodor? - Help Bran down the hall.
100,- Right. Give it here. - No!,Such a little thing.,That's not true. You killed the beast.,We're done for today. Go clean the armoury.
101,Put away your blade.,A bird without feathers.,You only spared the girl because of the love y...,That's all you're good for.
102,"- I take orders from your father, not you. - P...",They came to take his body away,"I didn't, I...",- Well fought! - Piss off.
103,"I'm sorry, Bran.","and Robert held me. I screamed and I battled, ...","When Aerys Targaryen sat on the iron throne, y...",- Did he hurt you? - I've had worse.
104,Lord Stark?,That little bundle.,Someday you'll sit on the throne and the truth...,You can call me Sam... if you want.
105,There are five pups.,They took him away and I never saw him again.,Do I have to marry her?,- My mother calls me Sam. - It's not going to ...
106,One for each of the Stark children.,"Never have visited the crypt, never.",Yes.,- You're going to have to defend yourself. - W...
107,The direwolf is the sigil of your house.,I pray to the Mother every morning and night,She's very beautiful and young.,I wanted to.

In [34]:
got_seleccion.to_json(
    r"C:\Users\jorge\OneDrive\Escritorio\TAREAM28\got_seleccion.json",
    orient="records",
    indent=4
)

print("Archivo got_seleccion.json creado correctamente.")

Archivo got_seleccion.json creado correctamente.